In [1]:
import numpy as np

my_list = [1,2,3,4]
print(type(np.array(my_list)))

arr = np.array(my_list)

print(arr)



<class 'numpy.ndarray'>
[1 2 3 4]


In [2]:
r1 = np.arange(0,10)
print(r1)
r2 = np.arange(0,10,2)
print(r2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [3]:
#np.zeros(5)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
print(np.ones(5))
print('\n')
print(np.ones((5,5)))


[1. 1. 1. 1. 1.]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print(np.random.randint(0,10))
print('\n')
print(np.random.randint(0,1000,(3,5)))

9


[[802 970 978 981 329]
 [527  34 982 862  20]
 [904 679 190 217 269]]


In [6]:
arr =np.random.randint(0,100,10)
print(arr)

[99 91  0 53 24 34 24 82 68 26]


In [7]:
np.random.seed(101)     # Random number ke fixed kore deya
arr =np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [8]:
np.random.seed(101)     # Random number ke fixed kore deya
arr =np.random.randint(0,100,10)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.argmax()) # Maxmimum number ka index value = 95 er 0
print(arr.argmin()) # Maxnimum number ka index value = 9 er 7
print(arr.reshape(2,5))

[95 11 81 70 63 87 75  9 77 40]
95
9
60.8
0
7
[[95 11 81 70 63]
 [87 75  9 77 40]]


In [9]:

import numpy as np

my_list = [1,2,3,4]
print('\n')
mat = np.arange(0,100).reshape(10,10)
print(mat)
print('\n')
print(mat[2,2])
print(mat[0,:]) #row
print(mat[:,0] )#col
print(mat[0:3,0:3])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


22
[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
