In [2]:
import numpy as np

# Basic

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [14]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3])

In [6]:
a.ndim

1

In [8]:
b = np.array([[1,2,3],[2,3,4]], dtype='int32')
b

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
b.shape

(2, 3)

In [15]:
a.dtype

dtype('int32')

In [16]:
a.itemsize # n-1

4

In [17]:
a.nbytes

12

In [18]:
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5],[6,2,7,4,5]])

In [20]:
a

array([[1, 2, 3, 4, 5],
       [6, 2, 7, 4, 5]])

In [21]:
a[1,3]

4

In [22]:
a[0,:] # all row 

array([1, 2, 3, 4, 5])

In [23]:
a[:,0] 

array([1, 6])

In [24]:
a[:,2]

array([3, 7])

In [26]:
a[0,1:-1:2]

array([2, 4])

# 3d example

In [29]:
c = np.array([[[1,2],[3,4]],[[6,2],[5,4]]])
c

array([[[1, 2],
        [3, 4]],

       [[6, 2],
        [5, 4]]])

In [30]:
c[0,1,1]

4

In [31]:
c[:,1,:] = [[9,9],[8,8]]

In [32]:
c

array([[[1, 2],
        [9, 9]],

       [[6, 2],
        [8, 8]]])

In [34]:
# c[:,1,:] = [[9,9,9],[8,8]]

# Initializing Different Types of Arrays

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [39]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [41]:
np.random.rand(4,2)

array([[0.05480579, 0.23745407],
       [0.71387264, 0.91665951],
       [0.97240116, 0.72919065],
       [0.86577408, 0.38113721]])

In [43]:
np.random.randint(-4,8, size=(3,3))

array([[-2, -1, -1],
       [ 4, -2,  5],
       [ 3,  7, -4]])

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
arr = np.array([[1,2,3]])

In [46]:
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
r1 = np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

# Shallow Copy and Deep Copy

In [48]:
list1 = [[1,2,3],[1,8,3],[77,2,3]]

In [49]:
list2 = list1

In [50]:
list1

[[1, 2, 3], [1, 8, 3], [77, 2, 3]]

In [51]:
list2

[[1, 2, 3], [1, 8, 3], [77, 2, 3]]

In [52]:
list2[1][1] = 50

In [53]:
list2

[[1, 2, 3], [1, 50, 3], [77, 2, 3]]

In [54]:
list1

[[1, 2, 3], [1, 50, 3], [77, 2, 3]]

In [55]:
import copy

In [56]:
list3 = copy.copy(list1)

In [57]:
list3

[[1, 2, 3], [1, 50, 3], [77, 2, 3]]

In [58]:
list1

[[1, 2, 3], [1, 50, 3], [77, 2, 3]]

In [59]:
list3[1][1] = 'hi'

In [60]:
list3

[[1, 2, 3], [1, 'hi', 3], [77, 2, 3]]

In [61]:
list1

[[1, 2, 3], [1, 'hi', 3], [77, 2, 3]]

In [62]:
list4 = copy.deepcopy(list1)

In [63]:
list4[1][1] = 'try'

In [64]:
list4

[[1, 2, 3], [1, 'try', 3], [77, 2, 3]]

In [65]:
list1

[[1, 2, 3], [1, 'hi', 3], [77, 2, 3]]

# Math

In [66]:
a = np.array([1,2,3,4])

In [67]:
a + 2

array([3, 4, 5, 6])

In [68]:
a - 2

array([-1,  0,  1,  2])

In [69]:
a * 2

array([2, 4, 6, 8])

In [70]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [71]:
b = np.array([1,0,1,0])

In [72]:
a + b

array([2, 2, 4, 4])

In [73]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [74]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [75]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [76]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [79]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

# Statistics

In [80]:
sta = np.array([[1,2,3],[4,5,6]])
sta 

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.min(sta)

1

In [82]:
np.max(sta)

6

In [85]:
np.sum(sta, axis=1)

array([ 6, 15])

In [86]:
np.sum(sta, axis=0)

array([5, 7, 9])

# Reorganization Arrays

In [87]:
bf = np.array([[1,2,3,4],[4,5,6,7]])

In [88]:
bf

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [89]:
af = bf.reshape(4,2)

In [90]:
af

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [91]:
af = bf.reshape(4,3)
af

ValueError: cannot reshape array of size 8 into shape (4,3)

In [93]:
h = np.arange(0,12)

In [94]:
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
h.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,2,3,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 2, 3, 8],
       [1, 2, 3, 4],
       [5, 2, 3, 8]])

In [97]:
h1 = np.ones((2,4))
h2 = np.ones((2,2))

In [100]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [103]:
data = np.genfromtxt('data.txt', delimiter=',')
data = data.astype('int32')
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [104]:
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking And Advance Indexing

In [105]:
((data > 50) & (data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [106]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])